# Generated by Django 5.2.2 on 2025-06-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_game_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
