# Generated by Django 5.2.2 on 2025-06-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_paymentmethod_transaction_userbalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='card_last4',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='details',
            field=models.CharField(default=121212, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='type',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('qiwi', 'QIWI')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='UserBalance',
        ),
    ]
